# Generated by Django 3.1.2 on 2021-01-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('data', models.CharField(max_length=255, verbose_name='Reminders')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('updated_date_time', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
                ('dead_line', models.DateTimeField(verbose_name='Deadline')),
            ],
        ),
    ]
