# Generated by Django 3.1.2 on 2021-01-10 04:30

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_date_time',
        ),
        migrations.AlterField(
            model_name='todo',
            name='dead_line',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=django.utils.timezone.now)], verbose_name='Deadline'),
        ),
    ]
